//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST_DEV_JCL_03022022.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TOKA_DEVTESTEntities : DbContext
    {
        public TOKA_DEVTESTEntities()
            : base("name=TOKA_DEVTESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_PersonasFisicas> Tb_PersonasFisicas { get; set; }
        public virtual DbSet<TB_Usuarios> TB_Usuarios { get; set; }
    
        public virtual ObjectResult<sp_ActualizarPersonaFisica_Result> sp_ActualizarPersonaFisica(Nullable<int> idPersonaFisica, string nombre, string apellidoPaterno, string apellidoMaterno, string rFC, Nullable<System.DateTime> fechaNacimiento, Nullable<int> usuarioAgrega)
        {
            var idPersonaFisicaParameter = idPersonaFisica.HasValue ?
                new ObjectParameter("IdPersonaFisica", idPersonaFisica) :
                new ObjectParameter("IdPersonaFisica", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var usuarioAgregaParameter = usuarioAgrega.HasValue ?
                new ObjectParameter("UsuarioAgrega", usuarioAgrega) :
                new ObjectParameter("UsuarioAgrega", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ActualizarPersonaFisica_Result>("sp_ActualizarPersonaFisica", idPersonaFisicaParameter, nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, rFCParameter, fechaNacimientoParameter, usuarioAgregaParameter);
        }
    
        public virtual ObjectResult<sp_AgregarPersonaFisica_Result> sp_AgregarPersonaFisica(string nombre, string apellidoPaterno, string apellidoMaterno, string rFC, Nullable<System.DateTime> fechaNacimiento, Nullable<int> usuarioAgrega)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var usuarioAgregaParameter = usuarioAgrega.HasValue ?
                new ObjectParameter("UsuarioAgrega", usuarioAgrega) :
                new ObjectParameter("UsuarioAgrega", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AgregarPersonaFisica_Result>("sp_AgregarPersonaFisica", nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, rFCParameter, fechaNacimientoParameter, usuarioAgregaParameter);
        }
    
        public virtual ObjectResult<sp_EliminarPersonaFisica_Result> sp_EliminarPersonaFisica(Nullable<int> idPersonaFisica)
        {
            var idPersonaFisicaParameter = idPersonaFisica.HasValue ?
                new ObjectParameter("IdPersonaFisica", idPersonaFisica) :
                new ObjectParameter("IdPersonaFisica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EliminarPersonaFisica_Result>("sp_EliminarPersonaFisica", idPersonaFisicaParameter);
        }
    }
}
